# -*- coding: utf-8 -*-
"""Expectation Decider.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHSZlrP4R1X5c82VbKAEh5-RnUDFXyKL

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib_venn import venn2

"""Load Data"""

df = pd.read_csv("expectation_decider_dataset.csv")
df.head()

"""1. PROBABILITY EVENT EXAMPLES"""

# Event A: Student passes exam
event_pass = df[df["final_exam_pass"] == "Pass"]

# Event B: Student attends > 80%
event_attendance = df[df["attendance"] > 80]

# Event C: Participates in group discussion
event_group = df[df["group_discussion"] == "Yes"]

print(f"\nEvent A (Pass): {len(event_pass)} students")
print(f"Event B (Attendance > 80%): {len(event_attendance)} students")
print(f"Event C (Group Discussion): {len(event_group)} students")

"""2. EMPIRICAL PROBABILITY"""

# Calculate probability of passing
prob_pass = len(event_pass) / len(df)
print(f"\nEmpirical Probability of Passing: {prob_pass:.4f}")
print(f"This means {prob_pass * 100:.2f}% of students passed the exam")

""" 3. THEORETICAL PROBABILITY"""

# For Pass/Fail, theoretical probability (assuming equal likelihood)
theoretical_prob = 1 / 2
print(f"\nTheoretical Probability (Pass or Fail): {theoretical_prob:.4f}")
print(f"This assumes equal likelihood of passing and failing")

"""
 4. RANDOM VARIABLE & PROBABILITY DISTRIBUTION"""

# Create probability distribution table
pass_counts = df["final_exam_pass"].value_counts()
prob_dist = pass_counts / len(df)

print("\nProbability Distribution:")
print(prob_dist)

# Calculate mean and variance
mean = np.mean(df["final_exam_pass"] == "Pass")
variance = np.var(df["final_exam_pass"] == "Pass")

print(f"\nMean: {mean:.4f}")
print(f"Variance: {variance:.6f}")

"""5. VENN DIAGRAM"""

A = df[df["study_hours"] > 10]
B = df[df["attendance"] > 80]

A_and_B = df[(df["study_hours"] > 10) & (df["attendance"] > 80)]

len(A), len(B), len(A_and_B)

A_only = len(A) - len(A_and_B)
B_only = len(B) - len(A_and_B)
AB = len(A_and_B)

# Create Venn diagram
plt.figure()

venn2(
    subsets=(A_only, B_only, AB),
    set_labels=("Study > 10 hours/week", "Attendance > 80%")
)

plt.title("Venn Diagram of Study Hours and Attendance")
plt.show()

"""Contingency Table & Probability Calculations"""

contingency_table = pd.crosstab(
    df["group_discussion"],
    df["final_exam_pass"]
)

contingency_table

"""Joint Probability"""

joint_prob = contingency_table.loc["Yes", "Pass"] / len(df)
joint_prob

""" Marginal Probability"""

marginal_prob = pass_counts["Pass"] / len(df)
marginal_prob

""" Conditional Probability"""

conditional_prob = (
    contingency_table.loc["Yes", "Pass"] /
    contingency_table.loc["Yes"].sum()
)

conditional_prob

"""Interpret Conditional Probability"""

# Probabilities needed for relationship analysis
P_pass = (df["final_exam_pass"] == "Pass").mean()
P_pass_given_group = (
    (df[(df["group_discussion"] == "Yes") & (df["final_exam_pass"] == "Pass")].shape[0]) /
    (df[df["group_discussion"] == "Yes"].shape[0])
)

P_pass, P_pass_given_group

if conditional_prob != marginal_prob:
    result = "Events are Dependent"
else:
    result = "Events are Independent"

result

"""Bayes Theorem"""

P_H_given_P = 0.70
P_H = 0.60
P_P = marginal_prob

bayes_result = (P_H_given_P * P_P) / P_H
bayes_result